repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-toml

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
    - id: cargo-check
    - id: clippy

- repo: local
  hooks:
    - id: cargo-test
      name: cargo test
      description: Run cargo test
      entry: cargo test
      language: system
      types: [rust]
      pass_filenames: false
