name: Cross-Platform Build

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ferrum
            asset_name: ferrum-linux-amd64
          - os: windows-latest
            artifact_name: ferrum.exe
            asset_name: ferrum-windows-amd64.exe
          - os: macos-latest
            artifact_name: ferrum
            asset_name: ferrum-macos-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/release/${{ matrix.artifact_name }}
          if-no-files-found: error

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List artifacts
        run: find ./artifacts -type f | sort

      - name: Show detailed directory structure
        run: ls -la ./artifacts/*

      - name: Show exact file paths
        run: |
          echo "Linux binary path:"
          ls -la ./artifacts/ferrum-linux-amd64/
          echo "macOS binary path:"
          ls -la ./artifacts/ferrum-macos-amd64/
          echo "Windows binary path:"
          ls -la ./artifacts/ferrum-windows-amd64/

      - name: Prepare release assets
        run: |
          mkdir -p ./release-assets
          cp ./artifacts/ferrum-linux-amd64/ferrum ./release-assets/ferrum-linux-amd64
          cp ./artifacts/ferrum-macos-amd64/ferrum ./release-assets/ferrum-macos-amd64
          cp ./artifacts/ferrum-windows-amd64/ferrum.exe ./release-assets/ferrum-windows-amd64.exe
          chmod +x ./release-assets/ferrum-linux-amd64
          chmod +x ./release-assets/ferrum-macos-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release-assets/ferrum-linux-amd64
            ./release-assets/ferrum-macos-amd64
            ./release-assets/ferrum-windows-amd64.exe
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
